### ISSUE TITLE
Location of BitwardenRS Data Directory as an Environment Variable

### ISSUE THREAD

**Issue by obzerving** [ttionya/BitwardenRS-Backup#17]
If it wouldn't be too much of a hassle, could DATA_DIR be an environment variable? I've seen more than one set of installation instructions that used /data instead of /bitwarden/data.

**Comment by ttionya** [comment]
Thanks for the heads up, I will evaluate the workload and add the feature as soon as possible.

**Comment by mustaphazorgati** [comment]
If we use DATA_DIR as an environment variable we should also make `RESTORE_DIR` configurable.

@ttionya I don't think this is a lot of work. Shall I do it?

**Comment by ttionya** [comment]
> If we use DATA_DIR as an environment variable we should also make `RESTORE_DIR` configurable.
> 
> @ttionya I don't think this is a lot of work. Shall I do it?

Thanks, I am working on this change.

**Comment by obzerving** [comment]
Thanks for your consideration of this request.

**Comment by mustaphazorgati** [comment]
Hey @ttionya!
I just saw that you fixed this issue. Can you please extend the README so that new users know how to override the default data directory and other variables? Thanks!

**Comment by ttionya** [comment]
Hey @obzerving ,

I released v1.6.0 and you can specify the data directory by modifying the environment variable.

But I think you need to modify it only when you use automatic backup, please check your usage scenario to avoid using it by mistake.

Please let me know if you have any problem.

**Comment by ttionya** [comment]
> Hey @ttionya!
> I just saw that you fixed this issue. Can you please extend the README so that new users know how to override the default data directory and other variables? Thanks!

I have added the description.

**Comment by obzerving** [comment]
I am indeed using automatic backup, so v1.6.0 should resolve the issue for me. Thanks, again.
