### ISSUE TITLE
Don't Use RESTORE_DIR in RESTORE_EXTRACT_DIR

### ISSUE THREAD

**Issue by mustaphazorgati** [ttionya/BitwardenRS-Backup#18]
I want to mount my `RESTORE_DIR` as a read only volume permanently.

Because the `RESTORE_EXTRACT_DIR` points to a subfolder of the `RESTORE_DIR` this is not possible.

Suggestion: point `RESTORE_EXTRACT_DIR` to `/extract`, since this folder is only needed temporary.

**Comment by ttionya** [comment]
Confirming this issue, I will recheck the directory and modify it along with the issue #17 .
