### ISSUE TITLE
How to set `MAIL_SMTP_VARIABLES` on `.env` file?

### ISSUE THREAD

**Issue by quyleanh** [ttionya/BitwardenRS-Backup#21]
Could anyone tell me how to set `MAIL_SMTP_VARIABLES` on `.env` file? Thank you.

**Comment by ttionya** [comment]
There is no difference between using the env file and setting it directly with environment variables, did you encounter any problems?

If you don't know how to send emails using `heirloom-mailx`, you can refer to https://www.systutorials.com/sending-email-from-mailx-command-in-linux-using-gmails-smtp/ or see it at https://github.com/ttionya/BitwardenRS-Backup#mail_smtp_variables for zoho's example.

**Comment by quyleanh** [comment]
So is this correct if I use this command?

```bash
sudo docker run -d \
  --restart=always \
  --name bitwardenrs_backup \
  --volumes-from=bitwarden \
  --mount type=volume,source=bitwardenrs-rclone-data,target=/config/ \
  -e RCLONE_REMOTE_NAME="onedrive" \
  -e DATA_DIR="/data" \
  -e RCLONE_REMOTE_DIR="/BitwardenBackup/" \
  -e CRON="5 * * * *" \
  -e ZIP_ENABLE="TRUE" \
  -e ZIP_PASSWORD="PassSworD!" \
  -e ZIP_TYPE="7z" \
  -e BACKUP_FILE_DATE_SUFFIX="%Y%m%d" \
  -e BACKUP_KEEP_DAYS="2" \
  -e TIMEZONE="UTC" \
  -e MAIL_SMTP_ENABLE="TRUE"
  -e MAIL_SMTP_VARIABLES="
    -S smtp-use-starttls \
    -S smtp=smtp://smtp.zoho.com:587 \
    -S smtp-auth=login \
    -S smtp-auth-user=<my-email-address> \
    -S smtp-auth-password=<my-email-password> \
    -S from=<my-email-address>"
  -e MAIL_TO="<destination-email-address>"
  -e MAIL_WHEN_SUCCESS="TRUE"
  -e MAIL_WHEN_FAILURE="TRUE"
  ttionya/bitwardenrs-backup:latest
```

and this one in `.env` file?

```
RCLONE_REMOTE_NAME="onedrive"
RCLONE_REMOTE_DIR="/BitwardenBackup/"
CRON="5 * * * *"
ZIP_ENABLE="TRUE"
ZIP_PASSWORD="PassSworD!"
ZIP_TYPE="7z"
BACKUP_FILE_DATE_SUFFIX="%Y%m%d"
BACKUP_KEEP_DAYS="2"
MAIL_SMTP_ENABLE="TRUE"
MAIL_SMTP_VARIABLES="
  -S smtp-use-starttls \
  -S smtp=smtp://smtp.zoho.com:587 \
  -S smtp-auth=login \
  -S smtp-auth-user=<my-email-address> \
  -S smtp-auth-password=<my-email-password> \
  -S from=<my-email-address>"
MAIL_TO="<destination-email-address>"
MAIL_WHEN_SUCCESS="TRUE"
MAIL_WHEN_FAILURE="TRUE"
TIMEZONE="UTC"
```

**Comment by ttionya** [comment]
I haven't tried it, but I don't think there is a problem with this command.

If it does, try writing `MAIL_SMTP_VARIABLES` to a line.

**Comment by hanisntsolo** [comment]
Any one looking for gmail this will work like a charm:
      MAIL_SMTP_VARIABLES: '-S smtp-use-starttls -S smtp=smtp://smtp.gmail.com:587 -S smtp-auth=login -S smtp-auth-user=ds.pratap1997@gmail.com -S smtp-auth-password=$GF_SMTP_PASSWORD -S from=ds.pratap1997@gmail.com'
