### ISSUE TITLE
RCLONE_REMOTE 双 / 造成删除旧备份失败

### ISSUE THREAD

**Issue by vungsung** [ttionya/BitwardenRS-Backup#22]
### 失败纪录
```
upload backup file to storage system
delete 10 days ago backup files
deleting "backup.20210321_0000.zip"
2021/04/04 00:00:10 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2021/04/04 00:00:11 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2021/04/04 00:00:11 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2021/04/04 00:00:11 Failed to delete: directory not found
delete "backup.20210321_0000.zip" failed
(...)
deleting "backup.20210325_0000.zip"
2021/04/04 00:00:23 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2021/04/04 00:00:24 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2021/04/04 00:00:24 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2021/04/04 00:00:24 Failed to delete: directory not found
delete "backup.20210325_0000.zip" failed
```

### 原因调查
https://github.com/ttionya/BitwardenRS-Backup/blob/master/scripts/includes.sh#L179: `RCLONE_REMOTE_DIR` 默认为 `/BitwardenBackup/` 
https://github.com/ttionya/BitwardenRS-Backup/blob/master/scripts/includes.sh#L182: 赋值给 `RCLONE_REMOTE`
https://github.com/ttionya/BitwardenRS-Backup/blob/master/scripts/backup.sh#L121: 删除文件名为 `${RCLONE_REMOTE}/${RCLONE_DELETE_FILE}`，`${RCLONE_REMOTE}` 後又加了一个 `/`，路径中包含两个 `/` 於是 rclone 报错

### 修补建议
https://github.com/ttionya/BitwardenRS-Backup/blob/master/scripts/includes.sh#L182: 赋值 `RCLONE_REMOTE` 时将末尾 `/` 去除 ([语法来源](https://stackoverflow.com/a/16623897/9182265))
```
RCLONE_REMOTE="${RCLONE_REMOTE_NAME}:${RCLONE_REMOTE_DIR%/}"
```

### 修补实测
```
upload backup file to storage system
delete 10 days ago backup files
deleting "backup.20210322_0000.zip"
deleting "backup.20210323_0000.zip"
deleting "backup.20210324_0000.zip"
deleting "backup.20210325_0000.zip"
```

**Comment by ttionya** [comment]
你好 @vungsung ，

我使用的是默認的 `RCLONE_REMOTE_DIR` `/BitwardenBackup/` 上傳到 OneDrive，但是沒有遇到你反饋的問題。

能告知一下你部署的系統（Windows / Linux）、RClone 版本以及存儲系統（OneDrive、Google Drive etc.）嗎？

**Comment by vungsung** [comment]
你好，

环境是直接用 Dockerfile 的，RClone 配置使用 Google Drive，版本信息如下：
```
bash-5.1# rclone version
rclone v1.54.0
- os/arch: linux/amd64
- go version: go1.15.7
```

**Comment by ttionya** [comment]
你好 @vungsung ，

我使用 Google Drive 進行了測試，發現在使用 GD delete 時，多餘的 `/` 會導致找不到目標文件，其他情況下，比如 OneDrive 能正常工作。

我看到了你的 PR #23 ,使用 `${xx%/}` 可以解決這個問題，但是我希望可以去除末尾所有的 `/` 防止後續可能出現的拼接問題，所以我使用 `sed` 進行了處理。這可以解決程序中可能出現的拼接問題，但是不能處理在設置 `RCLONE_REMOTE_DIR` 時，多輸入了 `/` 的問題，如（/BitwardenBackup//subdir/），但我認爲這足夠了。

我發佈了 `v1.6.2-beta.0` 版本，你可以嘗試使用它，如果沒有發現其他問題，我會儘快發佈正式版。

謝謝

**Comment by vungsung** [comment]
你好，

使用 `sed` 是个不错的做法。经过测试后，`v1.6.2-beta.0` 可以在我的环境中正常工作。谢谢

**Comment by ttionya** [comment]
你好，

正式版 `v1.6.2` 已經發佈。
