### ISSUE TITLE
Enable multiple remote destinations

### ISSUE THREAD

**Issue by clouetb** [ttionya/BitwardenRS-Backup#24]
Hi,

first, thank you for this tool which is great and works fine (thanks to an above the average documentation).

Since I'm a bit paranoid I modified your scripts to enable using multiple remote destinations. It was quite easy, and I just merged the RCLONE_REMOTE_NAME and the RCLONE_REMOTE_DIR to a single var RCLONE_REMOTE where I just pass the list of remote destinations in a loop.

Would you consider a PR on this small enhancement ?

**Comment by ttionya** [comment]
Hey @clouetb ,

Thank you for your approval of this project.

We do not have a plan to support setting up multiple remote storage systems as it is not necessary.

For the situation you are experiencing, I think using multiple backup services is a better approach, it allows you more freedom to set up the configuration of each remote storage system.

Although this backup image will only backup and copy files from the data folder. I haven't tested it, but I think there may be problems with files being taken up if multiple mirrors are working at the same time, so I would recommend staggering the cron times of multiple mirrors by a few minutes to prevent possible problems.

**Comment by clouetb** [comment]
Hi,

Actually the approach you propose was the one I tried first, but I ran into problems mainly because of the constrained environment I’m running my docker container. Also, the need for configuring several instances proved to be more work than the adaptation of the scripts. 

Anyway, I’m fine with maintaining this solution in parallel of yours.

**Comment by ttionya** [comment]
Hey @clouetb ,

While we still have no plans to support multiple remote storage systems, I am very interested in the problem you are having, can you describe it in a little more detail?

**Comment by clouetb** [comment]
When I tried to spawn multiple containers with multiple systemd services, my system turned out to be quite unstable. Nothing linked to your scripts, my machine (an arm64 Helios64 NAS) just lack the memory needed for adding a second instance of the container (I run quite a lot of services on just 4Gb).

Above all, I didn't like the idea of having to setup two different systemd services just for sending my zipfile to another location.
Have a look here, you will see how I addressed the issue https://github.com/ttionya/BitwardenRS-Backup/compare/master...clouetb:master
Now I just send the same zipfile to two cloud providers in the same run (Google drive and One drive in my case).
This has been working flawlessly since 3 days.

**Comment by ttionya** [comment]
Hey @clouetb ,

I understand the problem you are having. As a whole, using multiple instances of backup would solve your problem, it's just limited by the lack of memory on your machine, so hopefully the backup tool itself will provide backups to multiple remote storage systems.

Fortunately you have excellent programming skills and can extend the functionality you need based on this repository. This is just a backup tool and will not be updated frequently, you can get the latest updates from this repository regularly.

Also look forward to the future where you may upgrade your NAS so you don't need to maintain another set of backup tools manually.

Thanks!
